# Generated by Django 5.0.6 on 2024-05-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
