# Generated by Django 5.0.4 on 2024-05-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employee_email_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='task_link',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
